---

- name: write systemd
  copy:
    dest: "{{ k3s_systemd_servicefile }}"
    content: |
      [Unit]
      Description=Lightweight Kubernetes
      Documentation=https://k3s.io
      Wants=network-online.target
      After=network-online.target
      
      [Install]
      WantedBy=multi-user.target
      
      [Service]
      Type=notify
      EnvironmentFile={{ k3s_systemd_envfile }}
      KillMode=process
      Delegate=yes
      # Having non-zero Limit*s causes performance problems due to accounting overhead
      # in the kernel. We recommend using cgroups to do container-local accounting.
      LimitNOFILE=1048576
      LimitNPROC=infinity
      LimitCORE=infinity
      TasksMax=infinity
      TimeoutStartSec=0
      Restart=always
      RestartSec=5s
      ExecStartPre=-/sbin/modprobe br_netfilter
      ExecStartPre=-/sbin/modprobe overlay
      ExecStartPre=-/sbin/modprobe bridge
      ExecStart=/usr/local/bin/k3s \
          server \
          '--server={{ k3s_server }}' \
          '--token-file={{ k3s_token_file }}' \
          '--write-kubeconfig-mode=0644' \
          {{ k3s_systemd_server_adds }}
